# version: '3.7'

# services:
#   elasticsearch:
#     platform: linux/x86_
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
#     environment:
#       - discovery.type=single-node
#     ports:
#       - 9200:9200
#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.5.2-arm64
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - 5601:5601

version: '3.7'
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.5.3-arm64
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  fluent-bit:
    container_name: fluentbit-container
    image: fluent/fluent-bit:2.0.6
    environment:
      - FLB_ES_HOST=elasticsearch
      - FLB_ES_PORT=9200
    command:
      - /fluent-bit/bin/fluent-bit
      - --config=/etc/fluent-bit/fluent-bit.conf
    networks:
      - es-net
    ports:
      #- 2020:2020
      - 24224:24224
    volumes:
      - ./conf/:/etc/fluent-bit/:ro
networks:
  es-net:
    driver: bridge
